# Generated by Django 5.1 on 2025-11-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dulce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del dulce', max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del dulce', null=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del dulce', max_digits=10)),
                ('stock', models.PositiveIntegerField(help_text='Cantidad de unidades en stock')),
                ('categoria', models.CharField(help_text='Categoría del dulce (ej. Chocolates, Gomas, Caramelos)', max_length=50)),
                ('fecha_disponibilidad', models.DateField(help_text='Fecha a partir de la cual el dulce está disponible')),
            ],
        ),
    ]
