# Generated by Django 5.1 on 2025-11-11 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dulces', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_envio', models.CharField(max_length=50)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=30)),
                ('metodo_pago', models.CharField(max_length=30)),
                ('id_pedido', models.CharField(max_length=100, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dulces.cliente')),
                ('dulce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dulces.dulce')),
            ],
        ),
    ]
