# Generated by Django 5.1 on 2025-11-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dulces', '0003_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('puesto', models.CharField(help_text='Puesto del empleado (ej. Cajero, Repartidor)', max_length=100)),
                ('fecha_contratacion', models.DateField(help_text='Fecha de contratación')),
                ('salario', models.DecimalField(decimal_places=2, help_text='Salario del empleado', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del ingrediente', max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del ingrediente', null=True)),
                ('unidad_medida', models.CharField(help_text='Unidad de medida (ej. kg, litros, unidades)', max_length=50)),
                ('stock', models.PositiveIntegerField(help_text='Cantidad en stock')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad', max_digits=10)),
                ('fecha_caducidad', models.DateField(blank=True, help_text='Fecha de caducidad', null=True)),
                ('proveedor', models.ForeignKey(help_text='Proveedor del ingrediente', on_delete=django.db.models.deletion.CASCADE, to='app_dulces.proveedor')),
            ],
        ),
    ]
