from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio_dulceria, name='inicio_dulceria'),
    path('agregar_dulce/', views.agregar_dulce, name='agregar_dulce'),
    path('ver_dulces/', views.ver_dulces, name='ver_dulces'),
    path('actualizar_dulce/<int:id>/', views.actualizar_dulce, name='actualizar_dulce'),
    path('realizar_actualizacion_dulce/<int:id>/', views.realizar_actualizacion_dulce, name='realizar_actualizacion_dulce'),
    path('borrar_dulce/<int:id>/', views.borrar_dulce, name='borrar_dulce'),
    path('realizar_borrado_dulce/<int:id>/', views.realizar_borrado_dulce, name='realizar_borrado_dulce'),
    path('agregar_cliente/', views.agregar_cliente, name='agregar_cliente'),
    path('ver_clientes/', views.ver_clientes, name='ver_clientes'),
    path('actualizar_cliente/<int:id>/', views.actualizar_cliente, name='actualizar_cliente'),
    path('realizar_actualizacion_cliente/<int:id>/', views.realizar_actualizacion_cliente, name='realizar_actualizacion_cliente'),
    path('borrar_cliente/<int:id>/', views.borrar_cliente, name='borrar_cliente'),
    path('realizar_borrado_cliente/<int:id>/', views.realizar_borrado_cliente, name='realizar_borrado_cliente'),
    path('agregar_Pedido/', views.agregar_Pedido, name='agregar_Pedido'),
    path('ver_Pedido/', views.ver_Pedido, name='ver_Pedido'),
    path('actualizar_Pedido/<int:id>/', views.actualizar_Pedido, name='actualizar_Pedido'),
    path('realizar_actualizacion_Pedido/<int:id>/', views.realizar_actualizacion_Pedido, name='realizar_actualizacion_Pedido'),
    path('borrar_Pedido/<int:id>/', views.borrar_Pedido, name='borrar_Pedido'),
    path('realizar_borrado_Pedido/<int:id>/', views.realizar_borrado_Pedido, name='realizar_borrado_Pedido'),
    path('agregar_empleado/', views.agregar_empleado, name='agregar_empleado'),
    path('ver_empleados/', views.ver_empleados, name='ver_empleados'),
    path('actualizar_empleado/<int:id>/', views.actualizar_empleado, name='actualizar_empleado'),
    path('realizar_actualizacion_empleado/<int:id>/', views.realizar_actualizacion_empleado, name='realizar_actualizacion_empleado'),
    path('borrar_empleado/<int:id>/', views.borrar_empleado, name='borrar_empleado'),
    path('realizar_borrado_empleado/<int:id>/', views.realizar_borrado_empleado, name='realizar_borrado_empleado'),
    path('agregar_proveedor/', views.agregar_proveedor, name='agregar_proveedor'),
    path('ver_proveedores/', views.ver_proveedores, name='ver_proveedores'),
    path('actualizar_proveedor/<int:id>/', views.actualizar_proveedor, name='actualizar_proveedor'),
    path('realizar_actualizacion_proveedor/<int:id>/', views.realizar_actualizacion_proveedor, name='realizar_actualizacion_proveedor'),
    path('borrar_proveedor/<int:id>/', views.borrar_proveedor, name='borrar_proveedor'),
    path('realizar_borrado_proveedor/<int:id>/', views.realizar_borrado_proveedor, name='realizar_borrado_proveedor'),
    path('agregar_ingrediente/', views.agregar_ingrediente, name='agregar_ingrediente'),
    path('ver_ingredientes/', views.ver_ingredientes, name='ver_ingredientes'),
    path('actualizar_ingrediente/<int:id>/', views.actualizar_ingrediente, name='actualizar_ingrediente'),
    path('realizar_actualizacion_ingrediente/<int:id>/', views.realizar_actualizacion_ingrediente, name='realizar_actualizacion_ingrediente'),
    path('borrar_ingrediente/<int:id>/', views.borrar_ingrediente, name='borrar_ingrediente'),
    path('realizar_borrado_ingrediente/<int:id>/', views.realizar_borrado_ingrediente, name='realizar_borrado_ingrediente'),
]
